export enum ProfileErrorsCode {
    INCORRECT_USERDATA = 'INCORRECT_USERDATA',
    INCORRECT_AGE = 'INCORRECT_AGE',
    INCORRECT_CITY = 'INCORRECT_CITY',
    INCORRECT_USERNAME = 'INCORRECT_USERNAME',
    EMPTY_DATA = 'EMPTY_DATA',
    SERVER_ERROR = 'SERVER_ERROR',
}
