name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipline:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: alwais()
      - name: Linting typescript
        run: npm run lint:ts
        if: alwais()
      - name: Linting css
        run: npm run stylelint:scss
        if: alwais()
      - name: Unit testing
        run: npm run test:unit
        if: alwais()
      - name: Build storybook
        run: npm run storybook:build
        if: alwais()
      - name: Ui testing
        run: npm run test:ui:ci
