name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipline:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting css
        run: npm run stylelint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      - name: Build storybook
        run: npm run storybook:build
        if: always()
      - name: Run Loki (UI)
        run: npm run test:ui:ci
      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
            name: design-system
            path: .loki
